declare module 'react-titles/Title10';
declare module 'react-scroll';
declare module 'react-router-hash-link';
declare module 'react-bootstrap';
declare module 'reactstrap';
declare module 'react-router-dom';
declare module 'react-reveal/Fade';
declare module 'styled-components';
declare module 'rebass';
declare module 'styled-system'